project:
  name: quickstart-amazon-eks
  owner: quickstart-eng@amazon.com
  shorten_stack_name: true
  regions:
    - af-south-1
    - ap-east-1
    - ap-northeast-1
    - ap-northeast-2
    - ap-northeast-3
    - ap-south-1
    - ap-south-2
    - ap-southeast-1
    - ap-southeast-2
    - ap-southeast-3
    - ap-southeast-4
    - ca-central-1
    - eu-central-1
    - eu-central-2
    - eu-north-1
    - eu-south-1
    - eu-south-2
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - me-central-1
    - me-south-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - us-gov-east-1
    - us-gov-west-1
    - cn-north-1
    - cn-northwest-1
  template: templates/amazon-eks-entrypoint-new-vpc.template.yaml
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  package_lambda: true
  build_submodules: true
tests:
  defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
    regions:
      - me-south-1
  v1-23:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      KubernetesVersion: '1.23'
    regions:
      - eu-south-1
  v1-22:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      KubernetesVersion: '1.22'
    regions:
      - us-east-2
  public-endpoint:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
      LoadBalancerController: Disabled
    regions:
      - ap-northeast-2
  cluster-autoscaler:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      NodeGroupType: Unmanaged
      LoadBalancerController: Disabled
      ProvisionBastionHost: Disabled
    regions:
      - eu-central-1
      - us-west-2
  metrics-server:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      MetricsServer: Enabled
      LoadBalancerController: Disabled
      ProvisionBastionHost: Disabled
    regions:
      - ap-northeast-1
  cert-manager:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      CertManager: Enabled
      LoadBalancerController: Enabled
      ProvisionBastionHost: Disabled
    regions:
      - ap-south-1
  monitoring-prom-graf:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      PrometheusIntegration: Enabled
      GrafanaIntegration: Enabled
      CertManager: Enabled
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: Unmanaged
      LoadBalancerController: Disabled
      ProvisionBastionHost: Disabled
    regions:
      - ap-southeast-2
  2az:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: Unmanaged
      ProvisionBastionHost: Disabled
    regions:
      - cn-north-1
  govcloud:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
    regions:
      - us-gov-east-1
      - us-gov-west-1
  no-logging:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
      EKSClusterLoggingTypes: ''
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: Unmanaged
      LoadBalancerController: Disabled
    regions:
      - eu-west-2
  efs:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EfsStorageClass: Enabled
      NodeGroupType: Unmanaged
      LoadBalancerController: Disabled
      ProvisionBastionHost: Disabled
    regions:
      - ap-southeast-1
  fargate:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      FargateNamespaces: kube-system
      FargateLabels: app.kubernetes.io/name=aws-cluster-autoscaler
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: Unmanaged
      LoadBalancerController: Enabled
    regions:
      - us-east-1
  bottlerocket:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      NodeGroupOS: Bottlerocket
      NodeInstanceFamily: ARM
      NodeInstanceType: c6g.medium
      NodeGroupType: Unmanaged
      LoadBalancerController: Enabled
      ProvisionBastionHost: Disabled
    regions:
      - eu-west-1
  snyk:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      SnykIntegration: Enabled
      SnykIntegrationId: ---overridden---
      LoadBalancerController: Enabled
      ProvisionBastionHost: Disabled
    regions:
      - eu-west-3
  # TODO: Troubleshoot KubeStateMetricsService resource failures & re-enable
  # new-relic:
  #   parameters:
  #     AvailabilityZones: $[taskcat_genaz_3]
  #     EKSPublicAccessEndpoint: Enabled
  #     NewRelicIntegration: Enabled
  #     NewRelicLicenseKey: ---overridden---
  #     LoadBalancerController: Enabled
  #     ProvisionBastionHost: Disabled
  #   regions:
  #     - sa-east-1
  rancher:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      RancherIntegration: Enabled
      LoadBalancerController: Enabled
      ProvisionBastionHost: Disabled
    regions:
      - ap-east-1
  managed-node-group-ASC:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      TestSuite: Enabled
      ProvisionBastionHost: Disabled
      LoadBalancerController: Enabled
    regions:
      - af-south-1
  windows:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      TestSuite: Enabled
      NodeGroupOS: Windows
      NodeGroupType: Unmanaged
      LoadBalancerController: Enabled
    regions:
      - eu-north-1
  calico:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      NodeGroupType: Unmanaged
      LoadBalancerController: Disabled
      ProvisionBastionHost: Disabled
      CalicoIntegration: Enabled
    regions:
      - us-west-2
  # TODO: Troubleshoot CopyZips failures & re-enable
  # rafaysystems:
  #   parameters:
  #     AvailabilityZones: $[taskcat_genaz_3]
  #     NodeGroupType: Unmanaged
  #     LoadBalancerController: Disabled
  #     ProvisionBastionHost: Disabled
  #     RafaySysIntegration: Enabled
  #     RafaySysFirstName: override
  #     RafaySysLastName: override
  #     RafaySysOrganizationName: override
  #     RafaySysEmail: override
  #   regions:
  #     - ca-central-1
  spot:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      NodeGroupType: Unmanaged
      OnDemandPercentage: 0
      OnDemandBastionPercentage: 0
      ProvisionBastionHost: Enabled
    regions:
      - us-east-1
