// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Name                       *string                  `json:",omitempty"`
	RoleArn                    *string                  `json:",omitempty"`
	LambdaRoleName             *string                  `json:",omitempty"`
	Version                    *string                  `json:",omitempty"`
	KubernetesNetworkConfig    *KubernetesNetworkConfig `json:",omitempty"`
	ResourcesVpcConfig         *ResourcesVpcConfig      `json:",omitempty"`
	EnabledClusterLoggingTypes []string                 `json:",omitempty"`
	EncryptionConfig           []EncryptionConfigEntry  `json:",omitempty"`
	KubernetesApiAccess        *KubernetesApiAccess     `json:",omitempty"`
	Arn                        *string                  `json:",omitempty"`
	CertificateAuthorityData   *string                  `json:",omitempty"`
	ClusterSecurityGroupId     *string                  `json:",omitempty"`
	Endpoint                   *string                  `json:",omitempty"`
	EncryptionConfigKeyArn     *string                  `json:",omitempty"`
	OIDCIssuerURL              *string                  `json:",omitempty"`
	Tags                       []Tags                   `json:",omitempty"`
}

// KubernetesNetworkConfig is autogenerated from the json schema
type KubernetesNetworkConfig struct {
	ServiceIpv4Cidr *string `json:",omitempty"`
}

// ResourcesVpcConfig is autogenerated from the json schema
type ResourcesVpcConfig struct {
	SecurityGroupIds      []string `json:",omitempty"`
	SubnetIds             []string `json:",omitempty"`
	EndpointPublicAccess  *bool    `json:",omitempty"`
	EndpointPrivateAccess *bool    `json:",omitempty"`
	PublicAccessCidrs     []string `json:",omitempty"`
}

// EncryptionConfigEntry is autogenerated from the json schema
type EncryptionConfigEntry struct {
	Resources []string  `json:",omitempty"`
	Provider  *Provider `json:",omitempty"`
}

// Provider is autogenerated from the json schema
type Provider struct {
	KeyArn *string `json:",omitempty"`
}

// KubernetesApiAccess is autogenerated from the json schema
type KubernetesApiAccess struct {
	Roles []KubernetesApiAccessEntry `json:",omitempty"`
	Users []KubernetesApiAccessEntry `json:",omitempty"`
}

// KubernetesApiAccessEntry is autogenerated from the json schema
type KubernetesApiAccessEntry struct {
	Arn      *string  `json:",omitempty"`
	Username *string  `json:",omitempty"`
	Groups   []string `json:",omitempty"`
}

// Tags is autogenerated from the json schema
type Tags struct {
	Value *string `json:",omitempty"`
	Key   *string `json:",omitempty"`
}
