AWSTemplateFormatVersion: 2010-09-09
Description: Enable Windows support (qs-1r15gqig4).
Metadata:
  cfn-lint: { config: { ignore_checks: [W9002, W9003, W9004, W9006] } }
Parameters:
  ClusterName:
    Type: String
Resources:
  EnableWindowsIpam:
  # https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support
    Type: AWSQS::Kubernetes::Resource
    UpdateReplacePolicy: Delete
    DeletionPolicy: Retain
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: kube-system
      Manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: amazon-vpc-cni
        data:
          enable-windows-ipam: 'true'
