AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ClusterName:
    Type: String
Resources:
  Test:
    Type: "AWSQS::Kubernetes::Get"
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: kube-system
      Name: cm/aws-auth
      JsonPath: '{.data.mapRoles}'
Outputs:
  Response:
    Value: !GetAtt Test.Response
  Id:
    Value: !GetAtt Test.Id
