AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWSQS::Kubernetes::Get resource type

Globals:
  Function:
    Timeout: 60  # docker start-up times can be long for SAM CLI

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: awsqs_kubernetes_get.handlers.resource
      Runtime: python3.8
      CodeUri: build/

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: awsqs_kubernetes_get.handlers.test_entrypoint
      Runtime: python3.8
      CodeUri: build/

